CI: Enable flatpak builds for TEB on Linux

diff --git a/.github/workflows/build-project.yaml b/.github/workflows/build-project.yaml
--- a/.github/workflows/build-project.yaml
+++ b/.github/workflows/build-project.yaml
@@ -230,93 +230,95 @@ jobs:
           path: ${{ github.workspace }}/.ccache
           key: ${{ runner.os }}-${{ matrix.os }}-ccache-x86_64-${{ needs.check-event.outputs.config }}
 
-  #flatpak-build:
-  #  name: Flatpak 📦
-  #  runs-on: ubuntu-24.04
-  #  needs: check-event
-  #  defaults:
-  #    run:
-  #      shell: bash
-  #  env:
-  #    FLATPAK_BUILD_SHARE_PATH: flatpak_app/files/share
-  #  container:
-  #    image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.6
-  #    options: --privileged
-  #  steps:
-  #    - uses: actions/checkout@v4
-  #      with:
-  #        submodules: recursive
-  #        fetch-depth: 0
-  #        set-safe-directory: ${{ env.GITHUB_WORKSPACE }}
+  flatpak-build:
+    name: Flatpak 📦
+    runs-on: ubuntu-24.04
+    needs: check-event
+    defaults:
+      run:
+        shell: bash
+    env:
+      FLATPAK_BUILD_SHARE_PATH: flatpak_app/files/share
+    container:
+      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.6
+      options: --privileged
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          fetch-depth: 0
+          set-safe-directory: ${{ env.GITHUB_WORKSPACE }}
 
-  #    - name: Set Up Environment 🔧
-  #      id: setup
-  #      env:
-  #        GH_TOKEN: ${{ github.token }}
-  #      run: |
-  #        : Set Up Environment 🔧
-  #        if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
+      - name: Set Up Environment 🔧
+        id: setup
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          : Set Up Environment 🔧
+          if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
 
-  #        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
+          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
 
-  #        echo '::group::Install actions/gh-actions-cache'
-  #        gh extension install actions/gh-actions-cache
-  #        echo '::endgroup::'
+          echo '::group::Install actions/gh-actions-cache'
+          gh extension install actions/gh-actions-cache
+          echo '::endgroup::'
 
-  #        cache_key='flatpak-builder-${{ hashFiles('build-aux/**/*.json') }}'
-  #        cache_ref='master'
-  #        read -r key size unit _ ref _ <<< \
-  #          "$(gh actions-cache list -B ${cache_ref} --key "${cache_key}-x86_64" | head -1)"
+          cache_key='flatpak-builder-${{ hashFiles('build-aux/**/*.json') }}'
+          cache_ref='plugin'
+          read -r key size unit _ ref _ <<< \
+            "$(gh actions-cache list -B ${cache_ref} --key "${cache_key}-x86_64" | head -1)"
 
-  #        if [[ "${key}" ]]; then
-  #          echo "cacheHit=true" >> $GITHUB_OUTPUT
-  #        else
-  #          echo "cacheHit=false" >> $GITHUB_OUTPUT
-  #        fi
+          if [[ "${key}" ]]; then
+            echo "cacheHit=true" >> $GITHUB_OUTPUT
+          else
+            echo "cacheHit=false" >> $GITHUB_OUTPUT
+          fi
 
-  #        echo "cacheKey=${cache_key}" >> $GITHUB_OUTPUT
+          echo "cacheKey=${cache_key}" >> $GITHUB_OUTPUT
 
-  #    - name: Validate Flatpak manifest
-  #      uses: ./.github/actions/flatpak-builder-lint
-  #      with:
-  #        artifact: manifest
-  #        path: build-aux/com.obsproject.Studio.json
+      - name: Validate Flatpak manifest
+        uses: ./.github/actions/flatpak-builder-lint
+        with:
+          artifact: manifest
+          path: build-aux/com.obsproject.Studio.json
 
-  #    - name: Build Flatpak Manifest 🧾
-  #      uses: flathub-infra/flatpak-github-actions/flatpak-builder@e5fa5a8fe51d76f770ad9d240e4ad5898b1c6a53
-  #      with:
-  #        build-bundle: ${{ fromJSON(needs.check-event.outputs.package) }}
-  #        bundle: obs-studio-flatpak-${{ needs.check-event.outputs.commitHash }}.flatpak
-  #        manifest-path: ${{ github.workspace }}/build-aux/com.obsproject.Studio.json
-  #        cache: ${{ fromJSON(steps.setup.outputs.cacheHit) || (github.event_name == 'push' && github.ref_name == 'master')}}
-  #        restore-cache: ${{ fromJSON(steps.setup.outputs.cacheHit) }}
-  #        cache-key: ${{ steps.setup.outputs.cacheKey }}
-  #        mirror-screenshots-url: https://dl.flathub.org/media
+      - name: Build Flatpak Manifest 🧾
+        uses: flathub-infra/flatpak-github-actions/flatpak-builder@e5fa5a8fe51d76f770ad9d240e4ad5898b1c6a53
+        with:
+          build-bundle: ${{ fromJSON(needs.check-event.outputs.package) }}
+          bundle: obs-studio-teb-flatpak-${{ needs.check-event.outputs.commitHash }}.flatpak
+          branch: teb-beta
+          upload-artifact: true
+          manifest-path: ${{ github.workspace }}/build-aux/com.obsproject.Studio.json
+          cache: ${{ fromJSON(steps.setup.outputs.cacheHit) || (github.event_name == 'push' && github.ref_name == 'plugin')}}
+          restore-cache: ${{ fromJSON(steps.setup.outputs.cacheHit) }}
+          cache-key: ${{ steps.setup.outputs.cacheKey }}
+          mirror-screenshots-url: https://dl.flathub.org/media
 
-  #    - name: Validate AppStream
-  #      uses: ./.github/actions/flatpak-builder-lint
-  #      with:
-  #        artifact: appstream
-  #        path: ${{ env.FLATPAK_BUILD_SHARE_PATH }}/metainfo/com.obsproject.Studio.metainfo.xml
+      - name: Validate AppStream
+        uses: ./.github/actions/flatpak-builder-lint
+        with:
+          artifact: appstream
+          path: ${{ env.FLATPAK_BUILD_SHARE_PATH }}/metainfo/com.obsproject.Studio.metainfo.xml
 
-  #    - name: Verify Icon and Metadata in app-info
-  #      working-directory: ${{ env.FLATPAK_BUILD_SHARE_PATH }}
-  #      run: |
-  #        : Verify Icon and Metadata in app-info
-  #        test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "::error::Missing 128x128 icon in app-info"; exit 1; }
-  #        test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "::error::Missing com.obsproject.Studio.xml.gz in app-info"; exit 1; }
+      - name: Verify Icon and Metadata in app-info
+        working-directory: ${{ env.FLATPAK_BUILD_SHARE_PATH }}
+        run: |
+          : Verify Icon and Metadata in app-info
+          test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "::error::Missing 128x128 icon in app-info"; exit 1; }
+          test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "::error::Missing com.obsproject.Studio.xml.gz in app-info"; exit 1; }
 
-  #    - name: Validate build directory
-  #      uses: ./.github/actions/flatpak-builder-lint
-  #      with:
-  #        artifact: builddir
-  #        path: flatpak_app
+      - name: Validate build directory
+        uses: ./.github/actions/flatpak-builder-lint
+        with:
+          artifact: builddir
+          path: flatpak_app
 
-  #    - name: Validate repository
-  #      uses: ./.github/actions/flatpak-builder-lint
-  #      with:
-  #        artifact: repo
-  #        path: repo
+      - name: Validate repository
+        uses: ./.github/actions/flatpak-builder-lint
+        with:
+          artifact: repo
+          path: repo
 
   windows-build:
     name: Windows 🪟
